---
abstract: 'Synchronous MessagePack RPC client'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-MPRPC-Client
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::MessagePack: 0.08
  Try::Tiny: 0
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/typester/net-mprpc-client-perl.git
version: 0.01
